---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install htop
    package:
      name:
        - htop
        - stacer
        - vim
        - alacritty
        - bitwarden
        - spotify

